spring.application.name=projectmanagementsystem

spring.datasource.url=jdbc:postgresql://localhost:5432/project_management 
spring.datasource.username=postgres
spring.datasource.password=Nikhil@201

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=TokenKeyForMyProjectManagementSystem2026ForInfusyxInfotech

jwt.expiration=72400000

server.port=8080